import h5py
import pandas as pd
from sklearn.utils import shuffle
from sklearn.decomposition import PCA
import os

csv_file = r'H:\project\DeepSurv\DeepSurv.pytorch-master\new.csv'
df = pd.read_csv(csv_file)
df = df.drop(['Time_m'], axis=1)
'''
df = df.drop(['original_gldm_SmallDependenceLowGrayLevelEmphasis', 'original_glrlm_ShortRunLowGrayLevelEmphasis',
              'original_ngtdm_Coarseness', 'original_shape_Compactness1',
              'square_gldm_SmallDependenceLowGrayLevelEmphasis', 'square_ngtdm_Coarseness',
              'squareroot_glcm_JointEnergy', 'squareroot_gldm_SmallDependenceLowGrayLevelEmphasis',
              'squareroot_ngtdm_Coarseness', 'logarithm_gldm_SmallDependenceLowGrayLevelEmphasis',
              'logarithm_ngtdm_Coarseness', 'exponential_glcm_Idmn', 'exponential_glcm_Idn',
              'exponential_glcm_InverseVariance', 'exponential_gldm_SmallDependenceEmphasis',
              'exponential_gldm_SmallDependenceLowGrayLevelEmphasis', 'exponential_glszm_ZonePercentage',
              'wavelet-HHH_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-HHH_ngtdm_Coarseness',
              'wavelet-HHL_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-HHL_ngtdm_Coarseness',
              'wavelet-HLH_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-HLL_glcm_Idmn',
              'wavelet-HLL_gldm_LowGrayLevelEmphasis', 'wavelet-HLL_gldm_SmallDependenceLowGrayLevelEmphasis',
              'wavelet-HLL_glrlm_LongRunLowGrayLevelEmphasis', 'wavelet-HLL_glrlm_LowGrayLevelRunEmphasis',
              'wavelet-HLL_glrlm_ShortRunLowGrayLevelEmphasis', 'wavelet-HLL_glszm_LowGrayLevelZoneEmphasis',
              'wavelet-HLL_glszm_SmallAreaLowGrayLevelEmphasis', 'wavelet-HLL_ngtdm_Coarseness',
              'wavelet-LHH_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-LHH_ngtdm_Coarseness',
              'wavelet-LHL_glcm_Idmn', 'wavelet-LHL_gldm_LowGrayLevelEmphasis',
              'wavelet-LHL_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-LHL_glrlm_LongRunLowGrayLevelEmphasis',
              'wavelet-LHL_glrlm_LowGrayLevelRunEmphasis', 'wavelet-LHL_glrlm_ShortRunLowGrayLevelEmphasis',
              'wavelet-LHL_glszm_LowGrayLevelZoneEmphasis', 'wavelet-LHL_glszm_SmallAreaLowGrayLevelEmphasis',
              'wavelet-LHL_ngtdm_Coarseness', 'wavelet-LLH_glcm_Idmn',
              'wavelet-LLH_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-LLH_glszm_SmallAreaLowGrayLevelEmphasis',
              'wavelet-LLL_glcm_JointEnergy', 'wavelet-LLL_gldm_LowGrayLevelEmphasis',
              'wavelet-LLL_gldm_SmallDependenceLowGrayLevelEmphasis', 'wavelet-LLL_glrlm_LongRunLowGrayLevelEmphasis',
              'wavelet-LLL_glrlm_LowGrayLevelRunEmphasis', 'wavelet-LLL_glrlm_ShortRunLowGrayLevelEmphasis',
              'wavelet-LLL_glszm_GrayLevelNonUniformityNormalized', 'wavelet-LLL_glszm_LowGrayLevelZoneEmphasis',
              'wavelet-LLL_glszm_SmallAreaLowGrayLevelEmphasis', 'wavelet-LLL_ngtdm_Coarseness',
              'original_gldm_LowGrayLevelEmphasis', 'original_glrlm_LowGrayLevelRunEmphasis',
              'original_glszm_SmallAreaLowGrayLevelEmphasis', 'exponential_glcm_Id', 'wavelet-HHL_glcm_Idmn',
              'wavelet-LLL_gldm_LargeDependenceLowGrayLevelEmphasis', 'exponential_firstorder_90Percentile',
              'exponential_firstorder_Energy', 'exponential_gldm_LowGrayLevelEmphasis', 'exponential_ngtdm_Contrast',
              'wavelet-LLH_ngtdm_Coarseness', 'exponential_glcm_Idm', 'exponential_firstorder_Mean',
              'wavelet-HLH_glcm_Idmn', 'wavelet-HLH_ngtdm_Coarseness', 'wavelet-LLH_gldm_LowGrayLevelEmphasis',
              'wavelet-LLH_glrlm_LowGrayLevelRunEmphasis', 'wavelet-LLH_glrlm_ShortRunLowGrayLevelEmphasis',
              'log-sigma-0-5-mm-3D_glcm_Idmn', 'log-sigma-0-5-mm-3D_gldm_SmallDependenceLowGrayLevelEmphasis',
              'log-sigma-0-5-mm-3D_glrlm_ShortRunLowGrayLevelEmphasis', 'log-sigma-0-5-mm-3D_ngtdm_Coarseness',
              'log-sigma-1-5-mm-3D_glcm_Idmn', 'log-sigma-1-5-mm-3D_gldm_SmallDependenceLowGrayLevelEmphasis',
              'log-sigma-1-5-mm-3D_glszm_SmallAreaLowGrayLevelEmphasis', 'log-sigma-1-5-mm-3D_ngtdm_Coarseness',
              'log-sigma-2-5-mm-3D_glcm_Idmn', 'log-sigma-2-5-mm-3D_gldm_SmallDependenceLowGrayLevelEmphasis',
              'log-sigma-2-5-mm-3D_glrlm_ShortRunLowGrayLevelEmphasis',
              'log-sigma-2-5-mm-3D_glszm_SmallAreaLowGrayLevelEmphasis', 'log-sigma-3-5-mm-3D_glcm_Idmn',
              'log-sigma-3-5-mm-3D_gldm_SmallDependenceLowGrayLevelEmphasis',
              'log-sigma-3-5-mm-3D_glszm_SmallAreaLowGrayLevelEmphasis', 'log-sigma-4-5-mm-3D_glcm_Idmn',
              'log-sigma-4-5-mm-3D_gldm_SmallDependenceLowGrayLevelEmphasis',
              'wavelet-LHH_glcm_Idmn', 'log-sigma-0-5-mm-3D_glszm_SmallAreaLowGrayLevelEmphasis',
              'log-sigma-1-5-mm-3D_gldm_LowGrayLevelEmphasis', 'log-sigma-1-5-mm-3D_glrlm_LowGrayLevelRunEmphasis',
              'log-sigma-1-5-mm-3D_glrlm_ShortRunLowGrayLevelEmphasis',
              'log-sigma-1-5-mm-3D_glszm_LowGrayLevelZoneEmphasis', 'original_glrlm_LongRunLowGrayLevelEmphasis',
              'exponential_firstorder_Uniformity', 'exponential_glcm_MaximumProbability',
              'original_glszm_GrayLevelNonUniformityNormalized', 'original_glszm_LowGrayLevelZoneEmphasis',
              'wavelet-HHL_glrlm_ShortRunLowGrayLevelEmphasis', 'log-sigma-0-5-mm-3D_gldm_LowGrayLevelEmphasis',
              'log-sigma-0-5-mm-3D_glrlm_LowGrayLevelRunEmphasis', 'log-sigma-2-5-mm-3D_glrlm_LowGrayLevelRunEmphasis',
              'log-sigma-2-5-mm-3D_glszm_LowGrayLevelZoneEmphasis',
              'square_firstorder_Minimum', 'log-sigma-2-5-mm-3D_ngtdm_Coarseness',
              'log-sigma-4-5-mm-3D_glszm_SmallAreaLowGrayLevelEmphasis', 'exponential_firstorder_MeanAbsoluteDeviation',
              'wavelet-LLH_glszm_LowGrayLevelZoneEmphasis', 'exponential_firstorder_RobustMeanAbsoluteDeviation',
              'exponential_glcm_Autocorrelation', 'wavelet-LHH_glszm_LargeAreaLowGrayLevelEmphasis'], axis=1)
'''
df = shuffle(df)
l = int(len(df) * 0.3)
'''
df = pd.DataFrame(df, columns=['PatientID', 'Time_d', 'Event',
                               'original_firstorder_Uniformity',
                               'original_glcm_Id',
                               'original_glcm_Idm',
                               'original_glcm_Idmn',
                               'original_glcm_Idn',
                               'original_glcm_Imc1',
                               'original_glcm_InverseVariance',
                               'original_glcm_JointEnergy',
                               'original_glcm_MaximumProbability',
                               'original_gldm_DependenceNonUniformityNormalized',
                               'original_gldm_SmallDependenceEmphasis',
                               'original_glrlm_GrayLevelNonUniformityNormalized',
                               'original_glrlm_RunLengthNonUniformityNormalized',
                               'original_glrlm_RunPercentage',
                               'original_glrlm_RunVariance',
                               'original_glrlm_ShortRunEmphasis',
                               'original_glszm_ZonePercentage',
                               'square_glcm_Id',
                               'square_glcm_Idmn',
                               'square_glcm_Idn',
                               'square_glcm_Imc1',
                               'square_glcm_InverseVariance',
                               'square_gldm_SmallDependenceEmphasis',
                               'square_glrlm_GrayLevelNonUniformityNormalized',
                               'square_glrlm_LowGrayLevelRunEmphasis',
                               'square_glrlm_RunLengthNonUniformityNormalized',
                               'square_glrlm_ShortRunEmphasis',
                               'square_glrlm_ShortRunLowGrayLevelEmphasis',
                               'square_glszm_GrayLevelNonUniformityNormalized',
                               'square_glszm_LowGrayLevelZoneEmphasis',
                               'square_glszm_SmallAreaLowGrayLevelEmphasis',
                               'square_glszm_ZonePercentage',
                               'squareroot_firstorder_Uniformity',
                               'squareroot_glcm_Idmn',
                               'squareroot_glcm_Idn',
                               'squareroot_glcm_Imc1',
                               'squareroot_glcm_MaximumProbability',
                               'squareroot_gldm_DependenceNonUniformityNormalized',
                               'squareroot_gldm_LowGrayLevelEmphasis',
                               'squareroot_glrlm_GrayLevelNonUniformityNormalized',
                               'squareroot_glrlm_LongRunLowGrayLevelEmphasis',
                               'squareroot_glrlm_LowGrayLevelRunEmphasis',
                               'squareroot_glrlm_ShortRunLowGrayLevelEmphasis',
                               'squareroot_glszm_GrayLevelNonUniformityNormalized',
                               'squareroot_glszm_LowGrayLevelZoneEmphasis',
                               'squareroot_glszm_SmallAreaLowGrayLevelEmphasis',
                               'logarithm_firstorder_Uniformity',
                               'logarithm_glcm_Correlation',
                               'logarithm_glcm_Imc1',
                               'logarithm_glcm_InverseVariance',
                               'logarithm_glcm_JointEnergy',
                               'logarithm_glcm_MaximumProbability',
                               'logarithm_gldm_LowGrayLevelEmphasis',
                               'logarithm_glrlm_GrayLevelNonUniformityNormalized',
                               'logarithm_glrlm_LowGrayLevelRunEmphasis',
                               'logarithm_glrlm_RunLengthNonUniformityNormalized',
                               'logarithm_glrlm_RunPercentage',
                               'logarithm_glrlm_ShortRunEmphasis',
                               'logarithm_glrlm_ShortRunLowGrayLevelEmphasis',
                               'logarithm_glszm_GrayLevelNonUniformityNormalized',
                               'logarithm_glszm_SmallAreaLowGrayLevelEmphasis',
                               'exponential_glcm_Imc1',
                               'exponential_glcm_JointEnergy',
                               'exponential_gldm_DependenceNonUniformityNormalized',
                               'exponential_glrlm_RunLengthNonUniformityNormalized',
                               'exponential_glrlm_RunPercentage',
                               'exponential_glrlm_ShortRunEmphasis',
                               'exponential_glrlm_ShortRunLowGrayLevelEmphasis',
                               'wavelet-HHH_firstorder_Uniformity',
                               'wavelet-HHH_glcm_Correlation',
                               'wavelet-HHH_glcm_Id',
                               'wavelet-HHH_glcm_Idm',
                               'wavelet-HHH_glcm_Idmn',
                               'wavelet-HHH_glcm_Idn',
                               'wavelet-HHH_glcm_Imc1',
                               'wavelet-HHH_glcm_Imc2',
                               'wavelet-HHH_glcm_InverseVariance',
                               'wavelet-HHH_glcm_JointEnergy',
                               'wavelet-HHH_glcm_MaximumProbability',
                               'wavelet-HHH_gldm_DependenceNonUniformityNormalized',
                               'wavelet-HHH_gldm_SmallDependenceEmphasis',
                               'wavelet-HHH_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-HHH_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-HHH_glrlm_RunPercentage',
                               'wavelet-HHH_glrlm_ShortRunEmphasis',
                               'wavelet-HHH_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-HHH_glszm_ZonePercentage',
                               'wavelet-HHL_firstorder_Uniformity',
                               'wavelet-HHL_glcm_Correlation',
                               'wavelet-HHL_glcm_Id',
                               'wavelet-HHL_glcm_Idm',
                               'wavelet-HHL_glcm_Idn',
                               'wavelet-HHL_glcm_Imc1',
                               'wavelet-HHL_glcm_Imc2',
                               'wavelet-HHL_glcm_InverseVariance',
                               'wavelet-HHL_glcm_JointEnergy',
                               'wavelet-HHL_glcm_MaximumProbability',
                               'wavelet-HHL_gldm_DependenceNonUniformityNormalized',
                               'wavelet-HHL_gldm_SmallDependenceEmphasis',
                               'wavelet-HHL_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-HHL_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-HHL_glrlm_RunPercentage',
                               'wavelet-HHL_glrlm_ShortRunEmphasis',
                               'wavelet-HHL_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-HHL_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-HHL_glszm_SmallAreaEmphasis',
                               'wavelet-HHL_glszm_SmallAreaLowGrayLevelEmphasis',
                               'wavelet-HHL_glszm_ZonePercentage',
                               'wavelet-HLH_firstorder_Uniformity',
                               'wavelet-HLH_glcm_Correlation',
                               'wavelet-HLH_glcm_Id',
                               'wavelet-HLH_glcm_Idm',
                               'wavelet-HLH_glcm_Idn',
                               'wavelet-HLH_glcm_Imc1',
                               'wavelet-HLH_glcm_Imc2',
                               'wavelet-HLH_glcm_InverseVariance',
                               'wavelet-HLH_glcm_JointEnergy',
                               'wavelet-HLH_glcm_MaximumProbability',
                               'wavelet-HLH_gldm_DependenceNonUniformityNormalized',
                               'wavelet-HLH_gldm_SmallDependenceEmphasis',
                               'wavelet-HLH_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-HLH_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-HLH_glrlm_RunPercentage',
                               'wavelet-HLH_glrlm_ShortRunEmphasis',
                               'wavelet-HLH_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-HLH_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-HLH_glszm_SmallAreaEmphasis',
                               'wavelet-HLH_glszm_ZonePercentage',
                               'wavelet-HLL_firstorder_Uniformity',
                               'wavelet-HLL_glcm_Correlation',
                               'wavelet-HLL_glcm_Id',
                               'wavelet-HLL_glcm_Idm',
                               'wavelet-HLL_glcm_Idn',
                               'wavelet-HLL_glcm_Imc1',
                               'wavelet-HLL_glcm_Imc2',
                               'wavelet-HLL_glcm_InverseVariance',
                               'wavelet-HLL_glcm_JointEnergy',
                               'wavelet-HLL_glcm_MaximumProbability',
                               'wavelet-HLL_gldm_DependenceNonUniformityNormalized',
                               'wavelet-HLL_gldm_LargeDependenceLowGrayLevelEmphasis',
                               'wavelet-HLL_gldm_SmallDependenceEmphasis',
                               'wavelet-HLL_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-HLL_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-HLL_glrlm_RunPercentage',
                               'wavelet-HLL_glrlm_ShortRunEmphasis',
                               'wavelet-HLL_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-HLL_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-HLL_glszm_SmallAreaEmphasis',
                               'wavelet-HLL_glszm_ZonePercentage',
                               'wavelet-LHH_firstorder_Uniformity',
                               'wavelet-LHH_glcm_Correlation',
                               'wavelet-LHH_glcm_Id',
                               'wavelet-LHH_glcm_Idm',
                               'wavelet-LHH_glcm_Idn',
                               'wavelet-LHH_glcm_Imc1',
                               'wavelet-LHH_glcm_Imc2',
                               'wavelet-LHH_glcm_InverseVariance',
                               'wavelet-LHH_glcm_JointEnergy',
                               'wavelet-LHH_glcm_MaximumProbability',
                               'wavelet-LHH_gldm_DependenceNonUniformityNormalized',
                               'wavelet-LHH_gldm_SmallDependenceEmphasis',
                               'wavelet-LHH_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-LHH_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-LHH_glrlm_RunPercentage',
                               'wavelet-LHH_glrlm_ShortRunEmphasis',
                               'wavelet-LHH_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-LHH_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-LHH_glszm_SmallAreaEmphasis',
                               'wavelet-LHH_glszm_SmallAreaLowGrayLevelEmphasis',
                               'wavelet-LHH_glszm_ZonePercentage',
                               'wavelet-LHL_firstorder_Uniformity',
                               'wavelet-LHL_glcm_Correlation',
                               'wavelet-LHL_glcm_Id',
                               'wavelet-LHL_glcm_Idm',
                               'wavelet-LHL_glcm_Idn',
                               'wavelet-LHL_glcm_Imc1',
                               'wavelet-LHL_glcm_Imc2',
                               'wavelet-LHL_glcm_InverseVariance',
                               'wavelet-LHL_glcm_JointEnergy',
                               'wavelet-LHL_glcm_MaximumProbability',
                               'wavelet-LHL_gldm_DependenceNonUniformityNormalized',
                               'wavelet-LHL_gldm_SmallDependenceEmphasis',
                               'wavelet-LHL_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-LHL_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-LHL_glrlm_RunPercentage',
                               'wavelet-LHL_glrlm_RunVariance',
                               'wavelet-LHL_glrlm_ShortRunEmphasis',
                               'wavelet-LHL_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-LHL_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-LHL_glszm_SmallAreaEmphasis',
                               'wavelet-LHL_glszm_ZonePercentage',
                               'wavelet-LLH_firstorder_Uniformity',
                               'wavelet-LLH_glcm_Id',
                               'wavelet-LLH_glcm_Idm',
                               'wavelet-LLH_glcm_Idn',
                               'wavelet-LLH_glcm_InverseVariance',
                               'wavelet-LLH_glcm_JointEnergy',
                               'wavelet-LLH_glcm_MCC',
                               'wavelet-LLH_glcm_MaximumProbability',
                               'wavelet-LLH_gldm_DependenceNonUniformityNormalized',
                               'wavelet-LLH_gldm_SmallDependenceEmphasis',
                               'wavelet-LLH_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-LLH_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-LLH_glrlm_RunPercentage',
                               'wavelet-LLH_glrlm_ShortRunEmphasis',
                               'wavelet-LLH_glszm_GrayLevelNonUniformityNormalized',
                               'wavelet-LLH_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-LLH_glszm_SmallAreaEmphasis',
                               'wavelet-LLH_glszm_ZonePercentage',
                               'wavelet-LLL_firstorder_Uniformity',
                               'wavelet-LLL_glcm_Id',
                               'wavelet-LLL_glcm_Idm',
                               'wavelet-LLL_glcm_Idmn',
                               'wavelet-LLL_glcm_Idn',
                               'wavelet-LLL_glcm_Imc1',
                               'wavelet-LLL_glcm_Imc2',
                               'wavelet-LLL_glcm_InverseVariance',
                               'wavelet-LLL_glcm_MaximumProbability',
                               'wavelet-LLL_gldm_DependenceNonUniformityNormalized',
                               'wavelet-LLL_gldm_SmallDependenceEmphasis',
                               'wavelet-LLL_glrlm_GrayLevelNonUniformityNormalized',
                               'wavelet-LLL_glrlm_RunLengthNonUniformityNormalized',
                               'wavelet-LLL_glrlm_RunPercentage',
                               'wavelet-LLL_glrlm_RunVariance',
                               'wavelet-LLL_glrlm_ShortRunEmphasis',
                               'wavelet-LLL_glszm_SizeZoneNonUniformityNormalized',
                               'wavelet-LLL_glszm_SmallAreaEmphasis',
                               'wavelet-LLL_glszm_ZonePercentage',
                               'log-sigma-0-5-mm-3D_firstorder_Uniformity',
                               'log-sigma-0-5-mm-3D_glcm_Correlation',
                               'log-sigma-0-5-mm-3D_glcm_Id',
                               'log-sigma-0-5-mm-3D_glcm_Idm',
                               'log-sigma-0-5-mm-3D_glcm_Idn',
                               'log-sigma-0-5-mm-3D_glcm_Imc1',
                               'log-sigma-0-5-mm-3D_glcm_Imc2',
                               'log-sigma-0-5-mm-3D_glcm_InverseVariance',
                               'log-sigma-0-5-mm-3D_glcm_JointEnergy',
                               'log-sigma-0-5-mm-3D_glcm_MaximumProbability',
                               'log-sigma-0-5-mm-3D_gldm_DependenceNonUniformityNormalized',
                               'log-sigma-0-5-mm-3D_gldm_SmallDependenceEmphasis',
                               'log-sigma-0-5-mm-3D_glrlm_GrayLevelNonUniformityNormalized',
                               'log-sigma-0-5-mm-3D_glrlm_RunLengthNonUniformityNormalized',
                               'log-sigma-0-5-mm-3D_glrlm_RunPercentage',
                               'log-sigma-0-5-mm-3D_glrlm_ShortRunEmphasis',
                               'log-sigma-0-5-mm-3D_glszm_GrayLevelNonUniformityNormalized',
                               'log-sigma-0-5-mm-3D_glszm_SizeZoneNonUniformityNormalized',
                               'log-sigma-0-5-mm-3D_glszm_SmallAreaEmphasis',
                               'log-sigma-0-5-mm-3D_glszm_ZonePercentage',
                               'log-sigma-1-5-mm-3D_firstorder_Uniformity',
                               'log-sigma-1-5-mm-3D_glcm_Correlation',
                               'log-sigma-1-5-mm-3D_glcm_Id',
                               'log-sigma-1-5-mm-3D_glcm_Idm',
                               'log-sigma-1-5-mm-3D_glcm_Idn',
                               'log-sigma-1-5-mm-3D_glcm_Imc1',
                               'log-sigma-1-5-mm-3D_glcm_Imc2',
                               'log-sigma-1-5-mm-3D_glcm_InverseVariance',
                               'log-sigma-1-5-mm-3D_glcm_JointEnergy',
                               'log-sigma-1-5-mm-3D_glcm_MCC',
                               'log-sigma-1-5-mm-3D_glcm_MaximumProbability',
                               'log-sigma-1-5-mm-3D_gldm_DependenceNonUniformityNormalized',
                               'log-sigma-1-5-mm-3D_gldm_SmallDependenceEmphasis',
                               'log-sigma-1-5-mm-3D_glrlm_GrayLevelNonUniformityNormalized',
                               'log-sigma-1-5-mm-3D_glrlm_LongRunLowGrayLevelEmphasis',
                               'log-sigma-1-5-mm-3D_glrlm_RunLengthNonUniformityNormalized',
                               'log-sigma-1-5-mm-3D_glrlm_RunPercentage',
                               'log-sigma-1-5-mm-3D_glrlm_ShortRunEmphasis',
                               'log-sigma-1-5-mm-3D_glszm_ZonePercentage',
                               'log-sigma-2-5-mm-3D_firstorder_Uniformity',
                               'log-sigma-2-5-mm-3D_glcm_Correlation',
                               'log-sigma-2-5-mm-3D_glcm_Id',
                               'log-sigma-2-5-mm-3D_glcm_Idn',
                               'log-sigma-2-5-mm-3D_glcm_Imc2',
                               'log-sigma-2-5-mm-3D_glcm_JointEnergy',
                               'log-sigma-2-5-mm-3D_glcm_MCC',
                               'log-sigma-2-5-mm-3D_glcm_MaximumProbability',
                               'log-sigma-2-5-mm-3D_gldm_DependenceNonUniformityNormalized',
                               'log-sigma-2-5-mm-3D_gldm_LowGrayLevelEmphasis',
                               'log-sigma-2-5-mm-3D_glrlm_GrayLevelNonUniformityNormalized',
                               'log-sigma-2-5-mm-3D_glrlm_LongRunLowGrayLevelEmphasis',
                               'log-sigma-2-5-mm-3D_glrlm_RunLengthNonUniformityNormalized',
                               'log-sigma-2-5-mm-3D_glrlm_RunPercentage',
                               'log-sigma-2-5-mm-3D_glrlm_ShortRunEmphasis',
                               'log-sigma-2-5-mm-3D_glszm_GrayLevelNonUniformityNormalized',
                               'log-sigma-2-5-mm-3D_glszm_SizeZoneNonUniformityNormalized',
                               'log-sigma-2-5-mm-3D_glszm_SmallAreaEmphasis',
                               'log-sigma-3-5-mm-3D_glcm_Correlation',
                               'log-sigma-3-5-mm-3D_glcm_Idn',
                               'log-sigma-3-5-mm-3D_glcm_Imc1',
                               'log-sigma-3-5-mm-3D_glcm_Imc2',
                               'log-sigma-3-5-mm-3D_glcm_InverseVariance',
                               'log-sigma-3-5-mm-3D_glcm_JointEnergy',
                               'log-sigma-3-5-mm-3D_glcm_MCC',
                               'log-sigma-3-5-mm-3D_glcm_MaximumProbability',
                               'log-sigma-3-5-mm-3D_gldm_DependenceNonUniformityNormalized',
                               'log-sigma-3-5-mm-3D_gldm_LowGrayLevelEmphasis',
                               'log-sigma-3-5-mm-3D_glrlm_GrayLevelNonUniformityNormalized',
                               'log-sigma-3-5-mm-3D_glrlm_LowGrayLevelRunEmphasis',
                               'log-sigma-3-5-mm-3D_glrlm_RunPercentage',
                               'log-sigma-3-5-mm-3D_glrlm_ShortRunEmphasis',
                               'log-sigma-3-5-mm-3D_glrlm_ShortRunLowGrayLevelEmphasis',
                               'log-sigma-3-5-mm-3D_glszm_GrayLevelNonUniformityNormalized',
                               'log-sigma-3-5-mm-3D_glszm_LowGrayLevelZoneEmphasis',
                               'log-sigma-3-5-mm-3D_ngtdm_Coarseness',
                               'log-sigma-4-5-mm-3D_firstorder_Uniformity',
                               'log-sigma-4-5-mm-3D_glcm_Correlation',
                               'log-sigma-4-5-mm-3D_glcm_Idn',
                               'log-sigma-4-5-mm-3D_glcm_Imc1',
                               'log-sigma-4-5-mm-3D_glcm_Imc2',
                               'log-sigma-4-5-mm-3D_glcm_InverseVariance',
                               'log-sigma-4-5-mm-3D_glcm_MCC',
                               'log-sigma-4-5-mm-3D_gldm_LowGrayLevelEmphasis',
                               'log-sigma-4-5-mm-3D_glrlm_GrayLevelNonUniformityNormalized',
                               'log-sigma-4-5-mm-3D_glrlm_LongRunLowGrayLevelEmphasis',
                               'log-sigma-4-5-mm-3D_glrlm_LowGrayLevelRunEmphasis',
                               'log-sigma-4-5-mm-3D_glrlm_ShortRunLowGrayLevelEmphasis',
                               'log-sigma-4-5-mm-3D_glszm_GrayLevelNonUniformityNormalized',
                               'log-sigma-4-5-mm-3D_glszm_LowGrayLevelZoneEmphasis',
                               'log-sigma-4-5-mm-3D_ngtdm_Coarseness']).fillna(0)
'''
test_df = df.iloc[:l]
train_df = df.iloc[l:]
t = test_df.set_index(['PatientID']).to_csv('ours_test.csv')
train_df.to_csv('ours_train.csv', index='PatientID')
pca = PCA(n_components=10)

test_p = test_df['PatientID']
test_t = test_df['Time_d']
test_e = test_df['Event']
test_x = test_df.drop(['Event', 'Time_d', 'PatientID'], axis=1)

train_p = train_df['PatientID']
train_t = train_df['Time_d']
train_e = train_df['Event']
train_x = train_df.drop(['Event', 'Time_d', 'PatientID'], axis=1)

# test_x = pca.fit_transform(test_x)
# train_x = pca.fit_transform(train_x)

if os.path.exists('ours.h5'):
    os.remove('ours.h5')
    ours_f = h5py.File('ours.h5')
    ours_f.create_dataset('train/x', data=train_x)
    ours_f.create_dataset('train/t', data=train_t)
    ours_f.create_dataset('train/e', data=train_e)
    ours_f.create_dataset('test/x', data=test_x)
    ours_f.create_dataset('test/t', data=test_t)
    ours_f.create_dataset('test/e', data=test_e)
    ours_f.create_dataset('train/p', data=train_p)
    ours_f.create_dataset('test/p', data=test_p)
    ours_f.keys()
    ours_f.close()
else:
    ours_f = h5py.File('ours.h5')
    ours_f.create_dataset('train/x', data=train_x)
    ours_f.create_dataset('train/t', data=train_t)
    ours_f.create_dataset('train/e', data=train_e)
    ours_f.create_dataset('test/x', data=test_x)
    ours_f.create_dataset('test/t', data=test_t)
    ours_f.create_dataset('test/e', data=test_e)
    ours_f.create_dataset('train/p', data=train_p)
    ours_f.create_dataset('test/p', data=test_p)
    ours_f.keys()
    ours_f.close()
